#!/bin/bash

printf '[Unit]
Description=Mikrotik Admin Whitelist Creator
[Service]
Type=simple
ExecStart=/usr/local/bin/mtadmin
[Install]
WantedBy=multi-user.target
' | sudo tee /etc/systemd/system/mtadmin.service

printf '[Unit]
Description=Mikrotik Admin Whitelist Scheduler
[Timer]
OnCalendar=*:0/5
Unit=mtadmin.service
[Install]
WantedBy=multi-user.target
' | sudo tee /etc/systemd/system/mtadmin.timer

systemctl enable mtadmin.timer
systemctl start mtadmin.timer
